### ISSUE TITLE
Google Cloud : Create Credentials Steps Require Updating

### ISSUE THREAD

**Issue by arieljatib** [StackPointCloud/spc-content#7]
Looks like they might have updated the process for updating generating credentials. 

Applies to: 

1. [How to Create Auth Credentials on Google Container Engine (GKE)](https://stackpointcloud.com/community/tutorial/how-to-create-auth-credentials-on-google-container-engine-gke)
2. [How to Create Auth Credentials on Google Compute Engine (GCE)](https://stackpointcloud.com/community/tutorial/google-compute-engine-setup-and-authentication)

## Changes Observed
In the `Create Credentials` section, the screenshots did not match my experience. 

- The "Go To Credentials" button no longer exist.
- Create Service account option is now in a different location. 

![image](https://cloud.githubusercontent.com/assets/1958997/22309970/85fc3bc4-e31b-11e6-9cff-26068ab627da.png)

- The step, "In the Service Account Name field, give your account a name like spc-admin. For Role select Project > Owner." no longer seems to exist.

**Comment by erikabarcott** [comment]
Updated
